version: '3.9'

services:
    django:
        build: .
        ports:
            - 9000:8000
        volumes:
            - .:/app
        depends_on:
            - postgres

    postgres:
        image: postgres:15.2-alpine
        ports:
            - 5432:5432
        volumes:
            - ./database:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres
